# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ staging ]

# Environment variables available to all jobs and steps in this workflow
env:
  WEBIMPCO_SSH_PRIVATE_KEY: ${{ secrets.WEBIMPCO_SSH_PRIVATE_KEY }}

jobs:
  deploy_job:
    runs-on: ubuntu-latest
    name: build&deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v2

#       - name: Install Dependencies
#         run: npm install
        
#       - name: Run build
#         run: npm run build
        
      - name: deploy file to server
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          username: 'webimp'
          server: '${{ secrets.SERVER_IP }}'
          ssh_private_key: ${{ secrets.WEBIMPCO_SSH_PRIVATE_KEY }}
          port: 8288
          local_path: './*'
          remote_path: 'public_html/alvian'
          args: '-o ConnectTimeout=5'
                  
#     - name: deploy
#       uses: webimp/php-72-apache 
#       run: |
#         eval $(ssh-agent -s)
#         ssh-add <(echo "$WEBIMPCO_SSH_PRIVATE_KEY")
#         mkdir -p ~/.ssh
#         export THEME_PATH="/opt/bitnami/apps/wordpress/htdocs/wp-content/themes/visense"
#         rm -rf .git
#         && rm -rf .gitignore
#         && rm -rf ./vendor/
#         tar -cvzf ../theme.tgz -C $CI_PROJECT_DIR .
#         && cd ..
      
